config/routes.rb
Rails.application.routes.draw do
  resources :eldo_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  
  resources :mv_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  

  resources :mv_good_features
  
  get 'messages/index'
  post 'messages/contact'
  get 'main/index'

  resources :products do
    collection do
      get 'scan_models'
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end  

   root 'main#index'

end

app/models/eldo_good.rb
class EldoGood < Eldorado
  self.table_name = :goods
  
  validates :title, presence: true
  validates :category_id, presence: true

  has_many :eldo_good_features, foreign_key: "good_id"
  belongs_to :eldo_category, foreign_key: "category_id"
  
  scope :found_in_yandex, -> {where.not(yandex_id: nil)}
  scope :not_found_in_yandex, -> {where(yandex_id: nil)}
  scope :no_features, -> {joins(:eldo_good_features).where("good_features.good_id IS NULL")}
  
      
  def self.dedupe
    grouped = all.group_by{|good| [good.foreign_id] }
    grouped.values.each do |duplicates|
      first_one = duplicates.shift
      duplicates.each{|double| double.destroy}
    end
  end
end

app/controllers/eldo_goods_controller.rb
class EldoGoodsController < ApplicationController
  before_action :set_eldo_good, only: [:show, :edit, :update, :destroy, :reload_form, :custom_search]

  def index
    @categories = EldoCategory.all
#    @subcategories = EldoCategory.subcategories
    session[:eldo_without_ym_id] = true if params[:eldo_without_ym_id] == 'true'
    session[:eldo_without_ym_id] = false if params[:eldo_without_ym_id] == 'false'
    session[:eldo_grid] = params[:grid]
    
    session[:eldo_subcategory_id] = params[:subcategory_id] unless params[:subcategory_id].blank?
    session[:eldo_subcategory_id] = nil if params[:show_all] == 'true'
    
    @all_goods_count = EldoGood.count
    
    
    unless session[:eldo_subcategory_id].blank?
      @subcategory = @categories.find session[:eldo_subcategory_id].to_i
      @category = 
        if @subcategory.root?
          @subcategory
        else
          @categories.find @subcategory.parent_id.to_i 
        end

      @goods = 
        if @subcategory.root?
          EldoGood.where(category_id: @subcategory.children.map{|c| c.id})
        else
          @subcategory.eldo_goods          
        end       
    else  
      @goods = EldoGood.all
    end  
    
    @goods = @goods.not_found_in_yandex if session[:eldo_without_ym_id]
    
    if session[:eldo_grid].blank?
      @grid = initialize_grid(@goods, 
        name: 'g1',
        per_page: 20,
        enable_export_to_csv: true,
        csv_file_name: "eldorado_#{Time.now}",
        order: "price",
        order_direction: 'desc'
        )
    else
      grid = 
        if session[:eldo_grid].is_a? String
          JSON.parse(session[:eldo_grid])
        else
          session[:eldo_grid]
        end
      @grid = initialize_grid(@goods, 
        name: 'g1',
        per_page: 20,
        order: "#{grid[:order] || 'price'}",
        order_direction: "#{grid[:order_direction]  || 'desc'}",
        enable_export_to_csv: true,
        csv_file_name: "eldorado_#{Time.now}"
      )
    end
    

    export_grid_if_requested('g1' => 'eldo_goods_table_wice') do
      # usual render or redirect code executed if the request is not a CSV export request
    end

  end

  def show
    @result = get_model_info_from_yandex @good.yandex_id unless @good.yandex_id.blank?
  end

  def new
    @good = EldoGood.new
  end

  def edit
  end


  def create
    @good = EldoGood.new(eldo_good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to eldo_goods_url, notice: 'Eldo good was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @good.update(eldo_good_params)
        format.html { redirect_to eldo_goods_url, notice: 'Eldo good was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to eldo_goods_url, notice: 'Eldo good was successfully destroyed.' }
    end
  end
  
  def custom_search
    @searched = get_models_from_yandex URI.encode params[:search]
  end

  
  def reload_form; end

  private

    def set_eldo_good
      @good = EldoGood.find(params[:id])
    end


    def eldo_good_params
      params.require(:eldo_good).permit(:foreign_id, :title, :brend, :short_name, :image, :url, :bonus, :price, :is_yandex_model, :yandex_id, :category_id)
    end
end

app/helpers/eldo_goods_helper.rb
module EldoGoodsHelper
end

app/views/eldo_goods/_eldo_goods_table_wice.html.haml
:erb
  <%= grid(@grid, show_filters: :always, upper_pagination_panel: true) do |g|        
      
      g.column name: 'Ключ Эльдорадо', attribute: 'foreign_id' do |p|  
        p.foreign_id
      end                           
      
      g.column name: 'Фото', attribute: 'image', in_csv: false do |p|  
        image_tag(p.image, style: 'height: 30px')
      end                           

      g.column name: 'Категория', attribute: 'title', model: "MvCategory" do |p| 
        p.eldo_category.title
      end  

      g.column name: 'Бренд', attribute: 'brend' do |p| 
        p.brend
      end  

      g.column name: 'Наименование', attribute: 'title' do |p| 
        p.title
      end  

      g.column name: 'Короткое имя', attribute: 'short_name' do |p| 
        p.short_name
      end  

      g.column name: 'Цена', attribute: 'price' do |p| 
        p.price
      end  

      g.column name: 'Бонус', attribute: 'bonus' do |p| 
        p.bonus
      end  

      g.column name: 'Яндекс ID', attribute: 'yandex_id' do |p| 
        p.yandex_id                     
      end                 

      g.column in_csv: false do |p| 
        link_to "Наименования", p, remote: true, class: "btn btn-primary btn-xs", style: "width: 100%"
      end

      g.column in_csv: false do |p| 
        link_to 'Удалить', p, :method => :delete, :data => { :confirm => 'Точно?' }, class: "btn btn-danger btn-xs", style: "width: 100%"
      end

  end%>                         

app/views/eldo_goods/_form.html.haml
= form_for @good, html: { class: "well well-sm", role: "form" } do |f|
  - if @good.errors.any?
    #error_explanation
      %h2 Ошибок: #{@good.errors.count}
      %ul
        - @good.errors.full_messages.each do |msg|
          %li= msg

  .form-group.input-group
    %span.input-group-addon
      %i Наименование:
    = f.text_area :title, class: "form-control"
  .form-group.input-group
    %span.input-group-addon
      %i Короткое имя:
    = f.text_field :short_name, class: "form-control"
  .form-group.input-group
    %span.input-group-addon
      %i Идентификатор яндекса:       
    = f.text_field :yandex_id, class: "form-control"


  = f.submit 'Сохранить', class: "btn btn-primary"


  = link_to 'Вернуть', reload_form_eldo_good_path(@good), class: "btn btn-warning pull-right", remote: true

app/views/eldo_goods/_search_result.html.haml
- if @searched['pager']['total'] == 0
  .alert.alert-danger Нет информации
- else  
  .label.label-default 
  %table
    %thead
      %tr
        %th Наименование
        %th Идентификатор яндекса
        %th Цены
        %th 
    - @searched['models'].each do |model|
      %tbody
        %tr
          %td= link_to model['name'], "https://market.yandex.ru/product/#{model['id']}", target: "_blank"
          %td= model['id']
          %td 
            - if model['prices']
              (#{model['prices']['min']} ..  #{model['prices']['avg']} ..  #{model['prices']['max']})
          %td
            %button.btn.btn-success.btn-xs.pull-right.append_y_result{:data => {:yandex_id => "#{model['id']}", :yandex_name => "#{model['name']}"}} Применить


- unless @good.brend.blank?
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      y_name = y_name.replace /#{@good.brend}/ig, ""
      $("#eldo_good_short_name").val y_name.strip()
      $("#eldo_good_yandex_id").val $(this).data "yandex-id"
- else
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      $("#eldo_good_short_name").val y_name.strip()
      $("#eldo_good_yandex_id").val $(this).data "yandex-id"

app/views/eldo_goods/_show.html.haml
.row
  .col-md-3
    = image_tag @good.image

  .col-md-9
    %table
      %thead
        %tr
          %th Категория
          %th Эльдорадо Id
          %th Наименование
          %th Бренд
          %th Краткое имя
          %th Бонус
          %th Цена
          %th Yandex Id
      %tbody
        %tr
          %td
            = @good.eldo_category.parent.title
            %br
            = @good.eldo_category.title
          %td= @good.foreign_id
          %td= link_to @good.title, @good.url, target: "_blank" 
          %td= @good.brend
          %td= @good.short_name
          %td= @good.bonus
          %td= @good.price
          %td= @good.yandex_id

    .panel.panel-info
      .panel-heading 
        %strong Яндекс маркет
      .panel-body
        - if @result.blank?
          .alert.alert-danger Не найдено единственного результата по данным товара
        - else  
          %table
            %thead
              %tr
                %th Идентификатор яндекса
                %th Наименование
                %th Цены
                %th 
            %tbody
              %tr
                %td= @result['models'].first['id']
                %td= link_to @result['models'].first['name'], "https://market.yandex.ru/product/#{@result['models'].first['id']}", target: "_blank" 
                %td 
                  - if @result['models'].first['prices']
                    (#{@result['models'].first['prices']['min']} ..  #{@result['models'].first['prices']['avg']} ..  #{@result['models'].first['prices']['max']})
                %td
                  %button.btn.btn-success.btn-xs.pull-right.append_y_result{:data => {:yandex_id => "#{@result['models'].first['id']}", :yandex_name => "#{@result['models'].first['name']}"}} Применить


    = form_tag url_for(action: "custom_search", id: @good.id), class: "well well-sm", role: "form", remote: true do
      .form-group.input-group
        %span.input-group-addon
          %i Поисковый запрос:
        = text_field_tag :search, @good.short_name, class: "form-control"
        %span.input-group-btn
          = submit_tag 'Искать', class: "btn btn-primary"
      #search_result


    .panel.panel-primary
      .panel-heading Редактирование товара:
      .panel-body#form
        = render 'form'
      %span.btn.btn-default.pull-right.btn-xs#popup_close_btn Закрыть

:coffeescript
  $("#popup_close_btn").click ->
    $("#popup_content").html ""
    $("#popup").hide()

- unless @good.brend.blank?
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      y_name = y_name.replace /#{@good.brend}/ig, ""
      $("#eldo_good_short_name").val y_name.strip()
      $("#eldo_good_yandex_id").val $(this).data "yandex-id"
- else
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      $("#eldo_good_short_name").val y_name.strip()
      $("#eldo_good_yandex_id").val $(this).data "yandex-id"

app/views/eldo_goods/custom_search.js.haml
$("#search_result").html("#{j render 'search_result'}");

app/views/eldo_goods/edit.html.haml
%h1 Editing eldo_good

= render 'form'

= link_to 'Show', @eldo_good
\|
= link_to 'Back', eldo_goods_path

app/views/eldo_goods/index.html.haml
.page-header
  %h2 
    Эльдорадо.
    = @category.title if @category
    .label.label-default
      = @subcategory.title if @subcategory
      (#{@goods.size} из #{@all_goods_count})
.row
  .col-md-12
    .form-group.input-group
      = link_to "Показать все", eldo_goods_path(show_all: true), class: "btn btn-success form-control"

      %span.input-group-addon
        %i Выберите категорию
      = collection_select(:eldo_category, :id, @categories.roots, :id, :title, |
         {selected: @category ? @category.id : '', prompt: "Все"  }, {class: "form-control"} )
      %span.input-group-addon
        %i Выберите подкатегорию
      = select_tag(:eldo_subcategory_id, options_for_select(@categories.subcategories.map { |m| [m.title, m.id, { class: m.parent_id}] }, selected: @subcategory ? @subcategory.id : ''), |
         { prompt: "Все", class: "form-control"  })
      %span.input-group-addon
        %i Без Яндекс Id
        = check_box_tag :eldo_without_yandex_id, true, session[:eldo_without_ym_id]
      = link_to 'Характеристики CSV',"csv/eldorado_goods_features.csv", class: " btn btn-primary form-control" 

= render 'eldo_goods_table_wice'

app/views/eldo_goods/new.html.haml
%h1 New eldo_good

= render 'form'

= link_to 'Back', eldo_goods_path

app/views/eldo_goods/reload_form.js.haml
$("#form").html("#{j render "form"}")

app/views/eldo_goods/show.js.haml
$("#waiting").hide()
$("#popup_content").html("")
$("#popup").css("height","")
$("#popup").css("top","50px")
$("#popup_content").html("#{j render "show"}")
$("#popup").show()