config/routes.rb
Rails.application.routes.draw do
  resources :eldo_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  
  resources :mv_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  

  resources :mv_good_features
  
  get 'messages/index'
  post 'messages/contact'
  get 'main/index'

  resources :products do
    collection do
      get 'scan_models'
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end  

   root 'main#index'

end

app/models/eldo_category.rb
class EldoCategory < Eldorado
  self.table_name = :categories
  
  acts_as_nested_set
  
  default_scope { order(:title)}
  
  validates :title, presence: true, uniqueness: true
  
  #has_many :category_features
  has_many :eldo_goods, foreign_key: "category_id"

  scope :subcategories, -> { where.not(parent_id: nil)}
end

app/models/eldo_good.rb
class EldoGood < Eldorado
  self.table_name = :goods
  
  validates :title, presence: true
  validates :category_id, presence: true

  has_many :eldo_good_features, foreign_key: "good_id"
  belongs_to :eldo_category, foreign_key: "category_id"
  
  scope :found_in_yandex, -> {where.not(yandex_id: nil)}
  scope :not_found_in_yandex, -> {where(yandex_id: nil)}
  scope :no_features, -> {joins(:eldo_good_features).where("good_features.good_id IS NULL")}
  
      
  def self.dedupe
    grouped = all.group_by{|good| [good.foreign_id] }
    grouped.values.each do |duplicates|
      first_one = duplicates.shift
      duplicates.each{|double| double.destroy}
    end
  end
end

app/models/eldorado.rb
class Eldorado < ActiveRecord::Base
  self.abstract_class = true
  establish_connection configurations["eldorado"]
end

app/models/entity_type.rb
class EntityType < WorkBase
  
  scope :visible, -> { where(is_product: 1).order(:display_name)}
  scope :visible_with_products, -> { visible.select('entity_types.id, display_name').includes(:products).find_all { |et| et.products.size > 0 }}
  default_scope { visible }
  has_many :products
  
end

app/models/mv_category.rb
class MvCategory < Mvideo
  self.table_name = :categories
  
  acts_as_nested_set
  
  default_scope { order(:title)}
  
  validates :title, presence: true, uniqueness: true
  
  #has_many :category_features
  has_many :mv_goods, foreign_key: "category_id"

  scope :subcategories, -> { where.not(parent_id: nil)}
end

app/models/mv_good.rb
class MvGood < Mvideo
  self.table_name = :goods
  
  validates :title, presence: true
  validates :category_id, presence: true

  has_many :mv_good_features, foreign_key: "good_id"
  has_many :mv_quantities, foreign_key: "good_id"
  belongs_to :mv_category, foreign_key: "category_id"
  
  scope :found_in_yandex, -> {where.not(yandex_id: nil)}
  scope :not_found_in_yandex, -> {where(yandex_id: nil)}
  scope :no_features, -> {joins(:mv_good_features).where("good_features.good_id IS NULL")}
  
      
  def self.dedupe
    grouped = all.group_by{|good| [good.foreign_id] }
    grouped.values.each do |duplicates|
      first_one = duplicates.shift
      duplicates.each{|double| double.destroy}
    end
  end
  
end

app/models/mv_good_feature.rb
class MvGoodFeature < Mvideo
  self.table_name = :good_features
  
  validates :name, :title, presence: true
  
  belongs_to :mv_good, foreign_key: "good_id"
end

app/models/mv_quantity.rb
class MvQuantity < Mvideo
  self.table_name = :quantities
  
  validates :good_id, presence: true
  validates :store_id, presence: true

  belongs_to :mv_store, foreign_key: "store_id"
  belongs_to :mv_good, foreign_key: "good_id"
end

app/models/mv_store.rb
class MvStore < Mvideo
  self.table_name = :stores
  
  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
end

app/models/mvideo.rb
class Mvideo < ActiveRecord::Base
  self.abstract_class = true
  establish_connection configurations["mvideo"]
end

app/models/product.rb
class Product < WorkBase
#  scope :for_stock, -> { where("stock_quantity > 0")}
  scope :for_stock, -> { where("delivery_order = 1 or delivery_order = 2")}
  default_scope { for_stock }
  scope :no_yandex_id, -> {where("yandex_modelid IS NULL OR yandex_modelid = 0")}
  scope :in_stock, -> {where("stock_quantity > 0")}
  scope :scanned, -> {no_yandex_id.where(id: ScanModel.all.pluck(:product_id))}
  
  belongs_to :entity_type
  belongs_to :vendor, class_name: "SubVendor", foreign_key: "vendor_id"
  has_one :scan_model
  
  
end

app/models/scan_model.rb
class ScanModel < ActiveRecord::Base
  belongs_to :product
  
  before_save :check_uniq
  
  protected

  def check_uniq
    ScanModel.where(product_id: self.product_id).limit(1).destroy_all
  end
  
end

app/models/sub_vendor.rb
class SubVendor < WorkBase
  
  
  has_many :products, :class_name => 'Product', :foreign_key => 'vendor_id'
end

app/models/work_base.rb
class WorkBase < ActiveRecord::Base
  self.abstract_class = true
  establish_connection configurations["work_base"]
end

app/controllers/mv_goods_controller.rb
class MvGoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy, :reload_form, :custom_search]

  def index
    @categories = MvCategory.all
#    @subcategories = MvCategory.subcategories
    session[:mv_without_ym_id] = true if params[:mv_without_ym_id] == 'true'
    session[:mv_without_ym_id] = false if params[:mv_without_ym_id] == 'false'
    session[:mv_grid] = params[:grid]
    
    @all_goods_count = MvGood.count
    session[:mv_subcategory_id] = params[:subcategory_id] unless params[:subcategory_id].blank?
    session[:mv_subcategory_id] = nil if params[:show_all] == 'true'
    
    unless session[:mv_subcategory_id].blank?
      @subcategory = @categories.find session[:mv_subcategory_id].to_i
      @category = 
        if @subcategory.root?
          @subcategory
        else
          @categories.find @subcategory.parent_id.to_i 
        end
        
      @goods = 
        if @subcategory.root?
          MvGood.where(category_id: @subcategory.children.map{|c| c.id})
        else
          @subcategory.mv_goods          
        end
    else  
      @goods = MvGood.all
    end  
    
    @goods = @goods.not_found_in_yandex if session[:mv_without_ym_id]
    
    if session[:mv_grid].blank?
      @grid = initialize_grid(@goods, 
        name: 'g1',
        per_page: 20,
        enable_export_to_csv: true,
        csv_file_name: "mvideo_#{Time.now}",
        order: "price",
        order_direction: 'desc'
        )
    else
      grid = 
        if session[:mv_grid].is_a? String
          JSON.parse(session[:mv_grid])
        else
          session[:mv_grid]
        end
      @grid = initialize_grid(@goods, 
        name: 'g1',
        per_page: 20,
        order: "#{grid[:order] || 'price'}",
        order_direction: "#{grid[:order_direction]  || 'desc'}",
        enable_export_to_csv: true,
        csv_file_name: "mvideo_#{Time.now}"
      )
    end
    

    export_grid_if_requested('g1' => 'mv_goods_table_wice') do
      # usual render or redirect code executed if the request is not a CSV export request
    end
  end

  def show
    @result = get_model_info_from_yandex @good.yandex_id unless @good.yandex_id.blank?
  end

  def new
    @good = Good.new
  end

  def edit
  end

  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to mv_goods_url, notice: 'Good was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to mv_goods_url, notice: 'Good was successfully updated.' }
      else
        format.html { render :show }
      end
    end
  end


  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to mv_goods_url, notice: 'Good was successfully destroyed.' }
    end
  end
  
  def custom_search
    @searched = get_models_from_yandex URI.encode params[:search]
  end

  
  def reload_form; end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = MvGood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:mv_good).permit(:title, :brend, :short_name, :yandex_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/eldo_goods_helper.rb
module EldoGoodsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mv_stores_helper.rb
module MvStoresHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/mv_goods/_form.html.haml
= form_for @good, html: { class: "well well-sm", role: "form" } do |f|
  - if @good.errors.any?
    #error_explanation
      %h2 Ошибок: #{@good.errors.count}
      %ul
        - @good.errors.full_messages.each do |msg|
          %li= msg

  .form-group.input-group
    %span.input-group-addon
      %i Наименование:
    = f.text_area :title, class: "form-control"
  .form-group.input-group
    %span.input-group-addon
      %i Короткое имя:
    = f.text_field :short_name, class: "form-control"
  .form-group.input-group
    %span.input-group-addon
      %i Идентификатор яндекса:       
    = f.text_field :yandex_id, class: "form-control"


  = f.submit 'Сохранить', class: "btn btn-primary"


  = link_to 'Вернуть', reload_form_mv_good_path(@good), class: "btn btn-warning pull-right", remote: true

app/views/mv_goods/_mv_goods_features_wice.html.haml
:erb
  <%= grid(@features_grid, show_filters: :no, hide_csv_button: true) do |g|        
      
      g.column name: 'Id товара', attribute: 'good_id' do |p|  
        p.good_id
      end                           
      
      g.column name: 'Ключ МВидео', attribute: 'foreign_id', model: "MvGood", in_html: false do |p|  
        p.mv_good.foreign_id
      end                           
                            
      g.column name: 'Тип характеристики', attribute: 'title', in_html: false do |p| 
        p.title
      end  

      g.column name: 'Характеристика', attribute: 'name', in_html: false do |p| 
        p.name
      end  

      g.column name: 'Значение', attribute: 'sign', in_html: false do |p| 
        p.sign
      end  

  end%>                         

app/views/mv_goods/_mv_goods_table_wice.html.haml
:erb
  <%= grid(@grid, show_filters: :always, upper_pagination_panel: true) do |g|        
      
      g.column name: 'Ключ МВидео', attribute: 'foreign_id' do |p|  
        p.foreign_id
      end                           
      
      g.column name: 'Фото', attribute: 'image', in_csv: false do |p|  
        image_tag(p.image, style: 'height: 30px')
      end                           

      g.column name: 'Категория', attribute: 'title', model: "MvCategory" do |p| 
        p.mv_category.title
      end  

      g.column name: 'Бренд', attribute: 'brend' do |p| 
        p.brend
      end  

      g.column name: 'Наименование', attribute: 'title' do |p| 
        p.title
      end  

      g.column name: 'Короткое имя', attribute: 'short_name' do |p| 
        p.short_name
      end  

      g.column name: 'Цена', attribute: 'price' do |p| 
        p.price
      end  

      g.column name: 'Бонус', attribute: 'bonus' do |p| 
        p.bonus
      end  

      g.column name: 'Яндекс ID', attribute: 'yandex_id' do |p| 
        p.yandex_id                     
      end                 

      g.column in_csv: false do |p| 
        link_to "Наименования", p, remote: true, class: "btn btn-primary btn-xs", style: "width: 100%"
      end

      g.column in_csv: false do |p| 
        link_to 'Удалить', p, :method => :delete, :data => { :confirm => 'Точно?' }, class: "btn btn-danger btn-xs", style: "width: 100%"
      end

  end%>                         

app/views/mv_goods/_search_result.html.haml
- if @searched['pager']['total'] == 0
  .alert.alert-danger Нет информации
- else  
  .label.label-default 
  %table
    %thead
      %tr
        %th Наименование
        %th Идентификатор яндекса
        %th Цены
        %th 
    - @searched['models'].each do |model|
      %tbody
        %tr
          %td= link_to model['name'], "https://market.yandex.ru/product/#{model['id']}", target: "_blank"
          %td= model['id']
          %td 
            - if model['prices']
              (#{model['prices']['min']} ..  #{model['prices']['avg']} ..  #{model['prices']['max']})
          %td
            %button.btn.btn-success.btn-xs.pull-right.append_y_result{:data => {:yandex_id => "#{model['id']}", :yandex_name => "#{model['name']}"}} Применить


- unless @good.brend.blank?
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      y_name = y_name.replace /#{@good.brend}/ig, ""
      $("#mv_good_short_name").val y_name.strip()
      $("#mv_good_yandex_id").val $(this).data "yandex-id"
- else
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      $("#mv_good_short_name").val y_name.strip()
      $("#mv_good_yandex_id").val $(this).data "yandex-id"

app/views/mv_goods/_show.html.haml
.row
  .col-md-3
    = image_tag @good.image, style: "width: 200px"
    .well.well-sm#store_qtys
      %table
        %thead
          %tr
            %th Магазин
            %th Кол-во
        %tbody
          - @good.mv_quantities.each do |qty|
            %tr
              %td= qty.mv_store.title
              %td= qty.qty
      

  .col-md-9
    %table
      %thead
        %tr
          %th Категория
          %th МВидео Id
          %th Наименование
          %th Бренд
          %th Краткое имя
          %th Бонус
          %th Цена
          %th Yandex Id
      %tbody
        %tr
          %td
            = @good.mv_category.parent.title
            %br
            = @good.mv_category.title
          %td= @good.foreign_id
          %td= link_to @good.title, @good.url, target: "_blank" 
          %td= @good.brend
          %td= @good.short_name
          %td= @good.bonus
          %td= @good.price
          %td= @good.yandex_id

    .panel.panel-info
      .panel-heading 
        %strong Яндекс маркет
      .panel-body
        - if @result.blank?
          .alert.alert-danger Не найдено единственного результата по данным товара
        - else  
          %table
            %thead
              %tr
                %th Идентификатор яндекса
                %th Наименование
                %th Цены
                %th 
            %tbody
              %tr
                %td= @result['models'].first['id']
                %td= link_to @result['models'].first['name'], "https://market.yandex.ru/product/#{@result['models'].first['id']}", target: "_blank" 
                %td 
                  - if @result['models'].first['prices']
                    (#{@result['models'].first['prices']['min']} ..  #{@result['models'].first['prices']['avg']} ..  #{@result['models'].first['prices']['max']})
                %td
                  %button.btn.btn-success.btn-xs.pull-right.append_y_result{:data => {:yandex_id => "#{@result['models'].first['id']}", :yandex_name => "#{@result['models'].first['name']}"}} Применить


    = form_tag url_for(action: "custom_search", id: @good.id), class: "well well-sm", role: "form", remote: true do
      .form-group.input-group
        %span.input-group-addon
          %i Поисковый запрос:
        = text_field_tag :search, @good.short_name, class: "form-control"
        %span.input-group-btn
          = submit_tag 'Искать', class: "btn btn-primary"
      #search_result


    .panel.panel-primary
      .panel-heading Редактирование товара:
      .panel-body#form
        = render 'form'
      %span.btn.btn-default.pull-right.btn-xs#popup_close_btn Закрыть

:coffeescript
  $("#popup_close_btn").click ->
    $("#popup_content").html ""
    $("#popup").hide()

- unless @good.brend.blank?
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      y_name = y_name.replace /#{@good.brend}/ig, ""
      $("#mv_good_short_name").val y_name.strip()
      $("#mv_good_yandex_id").val $(this).data "yandex-id"
- else
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      $("#mv_good_short_name").val y_name.strip()
      $("#mv_good_yandex_id").val $(this).data "yandex-id"

app/views/mv_goods/custom_search.js.haml
$("#search_result").html("#{j render 'search_result'}");

app/views/mv_goods/edit.html.haml
%h1 Editing good

= render 'form'

= link_to 'Show', @good
\|
= link_to 'Back', goods_path

app/views/mv_goods/index.html.haml
.page-header
  %h2 
    МВидео.
    = @category.title if @category
    .label.label-default
      = @subcategory.title if @subcategory
      (#{@goods.size} из #{@all_goods_count})
.row
  .col-md-12
    .form-group.input-group
      = link_to "Показать все", mv_goods_path(show_all: true), class: "btn btn-success form-control"

      %span.input-group-addon
        %i Выберите категорию
      = collection_select(:category, :id, @categories.roots, :id, :title, |
         {selected: @category ? @category.id : '', prompt: "Все"  }, {class: "form-control"} )
      %span.input-group-addon
        %i Выберите подкатегорию
      = select_tag(:subcategory_id, options_for_select(@categories.subcategories.map { |m| [m.title, m.id, { class: m.parent_id}] }, selected: @subcategory ? @subcategory.id : ''), |
         { prompt: "Все", class: "form-control"  })
      %span.input-group-addon
        %i Без Яндекс Id
        = check_box_tag :mv_without_yandex_id, true, session[:mv_without_ym_id]
      = link_to 'Характеристики CSV',"csv/mvideo_goods_features.csv", class: " btn btn-primary form-control" 

= render 'mv_goods_table_wice'

app/views/mv_goods/new.html.haml
%h1 New good

= render 'form'

= link_to 'Back', goods_path

app/views/mv_goods/reload_form.js.haml
$("#form").html("#{j render "form"}")

app/views/mv_goods/show.html.haml
%p#notice= notice

%p
  %b Foreign:
  = @good.foreign_id
%p
  %b Title:
  = @good.title
%p
  %b Brend:
  = @good.brend
%p
  %b Short name:
  = @good.short_name
%p
  %b Image:
  = @good.image
%p
  %b Url:
  = @good.url
%p
  %b Bonus:
  = @good.bonus
%p
  %b Price:
  = @good.price
%p
  %b Is yandex model:
  = @good.is_yandex_model
%p
  %b Yandex:
  = @good.yandex_id
%p
  %b Category:
  = @good.category_id

= link_to 'Edit', edit_good_path(@good)
\|
= link_to 'Back', goods_path

app/views/mv_goods/show.js.haml
$("#waiting").hide()
$("#popup_content").html("")
$("#popup").css("height","")
$("#popup").css("top","50px")
$("#popup_content").html("#{j render "show"}")
$("#popup").show()