config/routes.rb
Rails.application.routes.draw do
  resources :eldo_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  
  resources :mv_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  

  resources :mv_good_features
  
  get 'messages/index'
  post 'messages/contact'
  get 'main/index'

  resources :products do
    collection do
      get 'scan_models'
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end  

   root 'main#index'

end

app/models/product.rb
class Product < WorkBase
#  scope :for_stock, -> { where("stock_quantity > 0")}
  scope :for_stock, -> { where("delivery_order = 1 or delivery_order = 2")}
  default_scope { for_stock }
  scope :no_yandex_id, -> {where("yandex_modelid IS NULL OR yandex_modelid = 0")}
  scope :in_stock, -> {where("stock_quantity > 0")}
  scope :scanned, -> {no_yandex_id.where(id: ScanModel.all.pluck(:product_id))}
  
  belongs_to :entity_type
  belongs_to :vendor, class_name: "SubVendor", foreign_key: "vendor_id"
  has_one :scan_model
  
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  
  before_action :set_product, only: [:show, :edit, :update, :reload_form]
#  require "addressable/uri"
  #RestClient.log = $stdout
  

  def index
    session[:without_ym_id] = true if params[:without_ym_id] == 'true'
    session[:without_ym_id] = false if params[:without_ym_id] == 'false'
    
    session[:in_stock] = true if params[:in_stock] == 'true'
    session[:in_stock] = false if params[:in_stock] == 'false'
    
    session[:grid] = params[:grid]
    session[:entity_type] = params[:entity_type_id] unless params[:entity_type_id].blank?
    session[:entity_type] = nil if params[:show_all] == 'true'
    
    @entity_types = EntityType.all#visible_with_products
    
    unless session[:entity_type].blank?
      @entity_type = EntityType.find(session[:entity_type])
      @products = @entity_type.products
    else  
      @products = Product.all
    end
    
    if session[:without_ym_id]
      @products = @products.no_yandex_id.includes(:vendor)
    else  
      @products = @products.includes(:vendor)
    end
    if session[:in_stock]
      @products = @products.in_stock.includes(:vendor)
    else  
      @products = @products.includes(:vendor)
    end
    
    @all_products =
      if session[:in_stock] && session[:without_ym_id]
        Product.no_yandex_id.in_stock.count
      elsif session[:in_stock] && !session[:without_ym_id]
        Product.in_stock.count
      elsif !session[:in_stock] && session[:without_ym_id]
        Product.no_yandex_id.count
      else
        Product.all.count
      end

    if session[:grid].blank?
      @grid = initialize_grid(@products, 
        per_page: 20,
        order: "price",
        order_direction: 'desc'
      )
    else
      grid = 
        if session[:grid].is_a? String
          JSON.parse(session[:grid])
        else
          session[:grid]
        end
      @grid = initialize_grid(@products, 
        per_page: 20,
        order: "#{grid[:order] || 'price'}",
        order_direction: "#{grid[:order_direction]  || 'desc'}",
      )
    end
    @quantity = @products.size
    #@products = @products.paginate(page: params[:page], per_page: 100)
  end



  def scan_models
    session[:grid] = params[:grid]
    
    @entity_types = EntityType.all#visible_with_products
    entity_type_id = params[:entity_type_id]
    @entity_type = EntityType.find(entity_type_id) unless entity_type_id.blank?
    @products_for_scan = Product.no_yandex_id.includes(:vendor)#.limit 300
    @products_for_scan = @products_for_scan.where(entity_type_id: @entity_type.id) if @entity_type
    
    @all_products = @products_for_scan.size
    
    if ScanModel.all.count == 0 or params[:new_scan]
      File.open("log/models.log", 'a') {|file| file.write Time.now; file.write " Начало \n" }
      threads = []
      @pass_scan = []
      @scan_groups = []
      0.upto(1) do |i| 
        @scan_groups << @products_for_scan.limit(@products_for_scan.size / 2).offset((@products_for_scan.size / 2)*i)
      end
      @scan_groups.each do |scans|
        threads << Thread.new do
          scans.each do |s|
            if find_product_yandex(s).any? 
              @pass_scan << s.id 
              ScanModel.create(product_id: s.id)
            end  
          end
        end
      end
      threads.each(&:join)

      File.open("log/models.log", 'a') {|file| file.write Time.now; file.write " Окончание \n \n" }
    end  
    @products = Product.scanned
    @products = @products.where( entity_type_id:  @entity_type.id ) if @entity_type
#    @products = Product.where(id: @products.map(&:id))
    @pass_scan_time = ScanModel.last.created_at + 3.hours
    if session[:grid].blank?
      @grid = initialize_grid(@products, 
        per_page: 20,
        order: "price",
        order_direction: 'desc'
      )
    else
#      render text: session[:grid]
      grid = 
        if session[:grid].class == "String"
          JSON.parse(session[:grid])
        else
          session[:grid]
        end
      @grid = initialize_grid(@products, 
        per_page: 20,
        order: "#{grid[:order] || 'price'}",
        order_direction: "#{grid[:order_direction] || 'desc'}",
      )
    end
    @quantity = @products.size
    
  end
  
  
  def show
    @result = find_product_yandex @product
  end

  def edit
  end


  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url(grid: session[:grid]) }
      else
        format.html { render :show }
      end
    end
  end

  def custom_search
    @searched = get_models_from_yandex URI.encode params[:search]
  end

  def reload_form
    
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
       params.require(:product).permit(:name, :short_name, :yandex_modelid)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product, html: { class: "well well-sm", role: "form" } do |f|
  - if @product.errors.any?
    #error_explanation
      %h2 Ошибок: #{@product.errors.count}
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .form-group.input-group
    %span.input-group-addon
      %i Наименование:
    = f.text_area :name, class: "form-control"
  .form-group.input-group
    %span.input-group-addon
      %i Короткое имя:
    = f.text_field :short_name, class: "form-control"
  .form-group.input-group
    %span.input-group-addon
      %i Идентификатор яндекса:       
    = f.text_field :yandex_modelid, class: "form-control"


  = f.submit 'Сохранить', class: "btn btn-primary"


  = link_to 'Вернуть', reload_form_product_path(@product), class: "btn btn-warning pull-right", remote: true

app/views/products/_products_table.html.haml
%table#products
  %thead
    %tr
      %th Модель
      %th Производитель
      %th Описание
      %th Код производителя
      %th yandex modelid
      %th Краткое наименование
      %th Цена
      %th Наименование
      %th 



  %tbody
    - @products.each do |product|
      %tr
        %td= product[:model_name]
        %td= product.vendor.name if product.vendor
        %td= product.description
        %td= product.vendor_code
        %td= product.yandex_modelid
        %td= product.short_name
        %td= product.price
        %td= product.name
        %td= link_to "Наименования", product, remote: true, class: "btn btn-primary btn-xs", style: "width: 100%"

app/views/products/_products_table_wice.html.haml
:erb
  <%= grid(@grid, show_filters: :always, upper_pagination_panel: true) do |g|        
      
      g.column name: 'Модель', attribute: 'model_name' do |p| 
        if p.vendor && p.entity_type 
          link_to p[:model_name], "http://polus.su/product/#{p.id}", target: "_blank" 

        end  
      end                           

      g.column name: 'Производитель', attribute: 'name', model: "SubVendor" do |p| 
        p.vendor.name if p.vendor                     
      end  

      g.column name: 'Описание', attribute: 'description' do |p| 
        p.description                     
      end  

      g.column name: 'Код производителя', attribute: 'vendor_code' do |p| 
        p.vendor_code                     
      end  

      g.column name: 'Яндекс ID', attribute: 'yandex_modelid' do |p| 
        p.yandex_modelid                     
      end                 

      g.column name: 'Краткое наименование', attribute: 'short_name' do |p| 
        p.short_name
      end  

      g.column name: 'Цена', attribute: 'price' do |p| 
        p.price
      end  

      g.column name: 'Наименование', attribute: 'name' do |p| 
        p.name
      end  

      g.column do |p| 
        link_to "Наименования", p, remote: true, class: "btn btn-primary btn-xs", style: "width: 100%"
      end
  end%>                         

app/views/products/_search_result.html.haml
- if @searched['pager']['total'] == 0
  .alert.alert-danger Нет информации
- else  
  .label.label-default 
  %table
    %thead
      %tr
        %th Наименование
        %th Идентификатор яндекса
        %th Цены
        %th 
    - @searched['models'].each do |model|
      %tbody
        %tr
          %td= link_to model['name'], "https://market.yandex.ru/product/#{model['id']}", target: "_blank"
          %td= model['id']
          %td 
            - if model['prices']
              (#{model['prices']['min']} ..  #{model['prices']['avg']} ..  #{model['prices']['max']})
          %td
            %button.btn.btn-success.btn-xs.pull-right.append_y_result{:data => {:yandex_id => "#{model['id']}", :yandex_name => "#{model['name']}"}} Применить

:coffeescript
  $(".append_y_result").click ->
    $("#product_short_name").val $(this).data "yandex-name"
    $("#product_yandex_modelid").val $(this).data "yandex-id"

app/views/products/_show.html.haml
%table
  %thead
    %tr
      %th Модель
      %th Производитель
      %th Код произв.
      %th yandex ID
      %th Краткое наим.
      %th Цена
      %th Наименование
  %tbody
    %tr
      %td= link_to @product[:model_name], "http://polus.su/product/#{@product.id}", target: "_blank" 
      %td= @product.vendor.name if @product.vendor
      %td= @product.vendor_code
      %td= @product.yandex_modelid
      %td= @product.short_name
      %td= @product.price
      %td= @product.name


= form_tag "/products/custom_search", class: "well well-sm", role: "form", remote: true do
  .form-group.input-group
    %span.input-group-addon
      %i Поисковый запрос:
    = text_field_tag :search, @product.short_name, class: "form-control"
    %span.input-group-btn
      = submit_tag 'Искать', class: "btn btn-primary"
  #search_result



.panel.panel-info
  .panel-heading 
    %strong
      Яндекс маркет. 
      - unless @result.blank?
        Поиск по: #{@result.first.third}
  .panel-body
    - if @result.blank?
      .alert.alert-danger Не найдено единственного результата по данным товара
    - else  
      - @result.each do |res|
        .label.label-default 
        %table
          %thead
            %tr
              %th Поисковый запрос
              %th Идентификатор яндекса
              %th Наименование
              %th Цены
              %th 
          - res.second['models'].each do |model|
            %tbody
              %tr
                %td
                  %strong
                    = res.first
                    (#{res.second['pager']['total']})
                %td= model['id']
                %td= link_to model['name'], "https://market.yandex.ru/product/#{model['id']}", target: "_blank"
                %td 
                  - if model['prices']
                    (#{model['prices']['min']} ..  #{model['prices']['avg']} ..  #{model['prices']['max']})
                %td
                  %button.btn.btn-success.btn-xs.pull-right.append_y_result{:data => {:yandex_id => "#{model['id']}", :yandex_name => "#{model['name']}"}} Применить

    - unless @results.blank?
      %button.btn.btn-info.btn-xs{:aria => {:expanded => "false", :controls => "multiple_results"}, :data => {:toggle => "collapse", :target => "#multiple_results"}} 
        Остальные найденые

      .row.collapse#multiple_results
        - @results.each do |results|
          %div{:class => "col-md-#{12 / @results.size}"}
            .label.label-default
              %strong= results.first
              (#{results.third})
            %table
              %thead
                %tr
                  %th Yandex Id
                  %th Наименование
                  %th Цены
                  %th 
              - results.second['models'].each do |model|
                %tbody
                  %tr
                    %td= model['id']
                    %td= link_to model['name'], "https://market.yandex.ru/product/#{model['id']}", target: "_blank"
                    %td 
                      - if model['prices']
                        = [model['prices']['min'], model['prices']['avg'], model['prices']['max']].join(', ')
                    %td
                      %button.btn.btn-success.btn-xs.pull-right.glyphicon.glyphicon-ok.append_y_result{:data => {:yandex_id => "#{model['id']}", :yandex_name => "#{model['name']}"}}

.panel.panel-primary
  .panel-heading Редактирование товара:
  .panel-body#form
    = render 'form'
  %span.btn.btn-default.pull-right.btn-xs#popup_close_btn Закрыть

:coffeescript
  $("#popup_close_btn").click ->
    $("#popup_content").html ""
    $("#popup").hide()

- if !@product.vendor.blank? && !@product.vendor.name.strip.blank?
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      y_name = y_name.replace /#{@product.vendor.name}/ig, ""
      $("#product_short_name").val y_name.strip()
      $("#product_yandex_modelid").val $(this).data "yandex-id"
- else
  :coffeescript
    $(".append_y_result").click ->
      y_name = $(this).data("yandex-name")
      $("#product_short_name").val y_name.strip()
      $("#product_yandex_modelid").val $(this).data "yandex-id"

app/views/products/custom_search.js.haml
$("#search_result").html("#{j render 'search_result'}");

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
.page-header
  %h2 
    Товары в категории 
    .label.label-default
      = @entity_type.display_name if @entity_type 
      = @quantity 
      из #{@all_products}
.row
  .col-md-8
    .form-group.input-group
      = link_to "Показать все", products_path(show_all: true), class: "btn btn-success form-control"
      %span.input-group-addon
        %i Выберите категорию
      = collection_select(:entity_type, :id, @entity_types, :id, :display_name, |
         {selected: @entity_type ? @entity_type.id : '', prompt: "Все"  }, {class: "form-control"} )
      %span.input-group-addon
        %i Без Яндекс Id
        = check_box_tag :without_yandex_id, true, session[:without_ym_id]
      %span.input-group-addon
        %i На складе
        = check_box_tag :in_stock, true, session[:in_stock]

    
/= will_paginate @products
= render 'products_table_wice'



/%td= link_to 'Edit', edit_product_path(product)

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/reload_form.js.haml
$("#form").html("#{j render "form"}")

app/views/products/scan_models.html.haml
.page-header
  %h2 Товары найденые в Яндекс маркете (без Яндекс ID): #{@quantity} из #{@all_products}
.row
  .col-md-6
    .form-group.input-group
      = link_to 'Показать все', scan_models_products_path, class: "btn btn-success form-control"
      %span.input-group-addon
        %i Выберите категорию
      = collection_select(:entity_type_scan, :id, @entity_types, :id, :display_name, | 
        {selected: @entity_type ? @entity_type.id : nil, prompt: 'Все' }, {class: "form-control"} )
  .col-md-6
    .form-group.input-group
      = link_to "Запустить проверку", scan_models_products_path(new_scan: true, entity_type_id: @entity_type ? @entity_type.id : nil), class: "btn btn-success"
      %strong Последняя проверка: #{@pass_scan_time.try(:to_datetime).strftime("%d.%m.%Y %H:%m")}

/= will_paginate @products
= render 'products_table_wice'



/%td= link_to 'Edit', edit_product_path(product)

app/views/products/show.js.haml
$("#waiting").hide()
$("#popup_content").html("")
$("#popup").css("height","")
$("#popup").css("top","50px")
$("#popup_content").html("#{j render "show"}")
$("#popup").show(0)