config/routes.rb
Rails.application.routes.draw do
  resources :eldo_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  
  resources :mv_goods do
    collection do
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end
  

  resources :mv_good_features
  
  get 'messages/index'
  post 'messages/contact'
  get 'main/index'

  resources :products do
    collection do
      get 'scan_models'
      post 'custom_search'
    end  
    member do
      get 'reload_form'
    end  
  end  

   root 'main#index'

end

app/models/eldo_category.rb
class EldoCategory < Eldorado
  self.table_name = :categories
  
  acts_as_nested_set
  
  default_scope { order(:title)}
  
  validates :title, presence: true, uniqueness: true
  
  #has_many :category_features
  has_many :eldo_goods, foreign_key: "category_id"

  scope :subcategories, -> { where.not(parent_id: nil)}
end

app/models/eldo_good.rb
class EldoGood < Eldorado
  self.table_name = :goods
  
  validates :title, presence: true
  validates :category_id, presence: true

  has_many :eldo_good_features, foreign_key: "good_id"
  belongs_to :eldo_category, foreign_key: "category_id"
  
  scope :found_in_yandex, -> {where.not(yandex_id: nil)}
  scope :not_found_in_yandex, -> {where(yandex_id: nil)}
  scope :no_features, -> {joins(:eldo_good_features).where("good_features.good_id IS NULL")}
  
      
  def self.dedupe
    grouped = all.group_by{|good| [good.foreign_id] }
    grouped.values.each do |duplicates|
      first_one = duplicates.shift
      duplicates.each{|double| double.destroy}
    end
  end
end

app/models/eldorado.rb
class Eldorado < ActiveRecord::Base
  self.abstract_class = true
  establish_connection configurations["eldorado"]
end

app/models/entity_type.rb
class EntityType < WorkBase
  
  scope :visible, -> { where(is_product: 1).order(:display_name)}
  scope :visible_with_products, -> { visible.select('entity_types.id, display_name').includes(:products).find_all { |et| et.products.size > 0 }}
  default_scope { visible }
  has_many :products
  
end

app/models/mv_category.rb
class MvCategory < Mvideo
  self.table_name = :categories
  
  acts_as_nested_set
  
  default_scope { order(:title)}
  
  validates :title, presence: true, uniqueness: true
  
  #has_many :category_features
  has_many :mv_goods, foreign_key: "category_id"

  scope :subcategories, -> { where.not(parent_id: nil)}
end

app/models/mv_good.rb
class MvGood < Mvideo
  self.table_name = :goods
  
  validates :title, presence: true
  validates :category_id, presence: true

  has_many :mv_good_features, foreign_key: "good_id"
  has_many :mv_quantities, foreign_key: "good_id"
  belongs_to :mv_category, foreign_key: "category_id"
  
  scope :found_in_yandex, -> {where.not(yandex_id: nil)}
  scope :not_found_in_yandex, -> {where(yandex_id: nil)}
  scope :no_features, -> {joins(:mv_good_features).where("good_features.good_id IS NULL")}
  
      
  def self.dedupe
    grouped = all.group_by{|good| [good.foreign_id] }
    grouped.values.each do |duplicates|
      first_one = duplicates.shift
      duplicates.each{|double| double.destroy}
    end
  end
  
end

app/models/mv_good_feature.rb
class MvGoodFeature < Mvideo
  self.table_name = :good_features
  
  validates :name, :title, presence: true
  
  belongs_to :mv_good, foreign_key: "good_id"
end

app/models/mv_quantity.rb
class MvQuantity < Mvideo
  self.table_name = :quantities
  
  validates :good_id, presence: true
  validates :store_id, presence: true

  belongs_to :mv_store, foreign_key: "store_id"
  belongs_to :mv_good, foreign_key: "good_id"
end

app/models/mv_store.rb
class MvStore < Mvideo
  self.table_name = :stores
  
  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
end

app/models/mvideo.rb
class Mvideo < ActiveRecord::Base
  self.abstract_class = true
  establish_connection configurations["mvideo"]
end

app/models/product.rb
class Product < WorkBase
#  scope :for_stock, -> { where("stock_quantity > 0")}
  scope :for_stock, -> { where("delivery_order = 1 or delivery_order = 2")}
  default_scope { for_stock }
  scope :no_yandex_id, -> {where("yandex_modelid IS NULL OR yandex_modelid = 0")}
  scope :in_stock, -> {where("stock_quantity > 0")}
  scope :scanned, -> {no_yandex_id.where(id: ScanModel.all.pluck(:product_id))}
  
  belongs_to :entity_type
  belongs_to :vendor, class_name: "SubVendor", foreign_key: "vendor_id"
  has_one :scan_model
  
  
end

app/models/scan_model.rb
class ScanModel < ActiveRecord::Base
  belongs_to :product
  
  before_save :check_uniq
  
  protected

  def check_uniq
    ScanModel.where(product_id: self.product_id).limit(1).destroy_all
  end
  
end

app/models/sub_vendor.rb
class SubVendor < WorkBase
  
  
  has_many :products, :class_name => 'Product', :foreign_key => 'vendor_id'
end

app/models/work_base.rb
class WorkBase < ActiveRecord::Base
  self.abstract_class = true
  establish_connection configurations["work_base"]
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mv_stores_helper.rb
module MvStoresHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_menu.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => "#bs-example-navbar-collapse-1"}}
        %span.sr-only Полюс
        %span.icon-bar
      %a.navbar-brand.bg-primary{:href => "/"} Polus.su
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav
        %li{:class => "#{'active' if controller_name == 'products' && action_name == 'index'}"}
          = link_to 'Polus. Все товары', products_path
        %li{:class => "#{'active' if controller_name == 'products' && action_name == 'scan_models'}"}
          = link_to 'Polus. Товары без Яндекс ID найденые в Яндекс маркете', scan_models_products_path
        %li{:class => "#{'active' if controller_name == 'mv_goods'}"}
          = link_to 'МВидео', mv_goods_path
        %li{:class => "#{'active' if controller_name == 'eldo_goods'}"}
          = link_to 'Эльдорадо', eldo_goods_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Полюс
    = stylesheet_link_tag    'application', media: 'all'#, 'data-turbolinks-track' => true
    = javascript_include_tag 'application'#, 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/menu'

  .container.content
    #waiting= image_tag "wait.gif"
    #popup.col-lg-offset-2.col-lg-8.col-md-offset-2.col-md-8.col-sm-offset-1.col-sm-10.well.well-sm
      #popup_head.col-md-12 
        %span 
        #popup_close.glyphicon.glyphicon-remove-circle
          
      #popup_content

    = yield